### ISSUE TITLE
yo can these get implemented?

### ISSUE THREAD

**Issue by laudiacay** [banyancomputer/banyan-shared-rs#80]
https://github.com/banyancomputer/banyan-shared-rs/blob/8d58d3c40fb68bb9058b739720337038f03ccded/src/eth.rs#L179

who's on this?
@amiller68 flagging so you're aware- is this in the CLI PR?

@jonahkaye

**Comment by amiller68** [comment]
It is not in the CLI PR (CLI didn't implement anything having to do with proofs). My guess is that this is @jonahkaye's wheelhouse

**Comment by laudiacay** [comment]
ok- @jonahkaye, this is urs
